### ISSUE TITLE
iOS build Unable to build 'StackProductPresentation' since it includes Swift source files

### ISSUE THREAD

**Issue by SalavatR** [defold/extender#313]
Hi!
try to build iOS, bob 1.4.7, with applovin plugin and got error on both 
	--build-server https://build-stage.defold.com  and without
	
Error:
```
com.defold.extender.ExtenderException: Unable to build 'StackProductPresentation' since it includes Swift source files
	at com.defold.extender.Extender.compilePodSourceFiles(Extender.java:766)
	at com.defold.extender.Extender.buildPods(Extender.java:812)
	at com.defold.extender.Extender.buildEngine(Extender.java:1977)
	at com.defold.extender.Extender.build(Extender.java:2336)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:115)
	at com.defold.extender.AsyncBuilder$$FastClassBySpringCGLIB$$3a887347.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

dependency link: https://github.com/HGPoint/defold-maxsdk/archive/refs/tags/11.11.2.4.zip
this pod causes error `pod 'AppLovinMediationBidMachineAdapter', '2.3.0.0.0'`

.project applovin config
```
[applovin]
sdk_key_ios = xxxx
ad_unit_rewarded = xxx
ad_unit_interstitial = xxx
ad_unit_banner = xxx
amazon_key = xxx
amazon_interstitial_slot = xxxx
amazon_banner_slot = xxxx
BidMachineAdapter = 1
```

build command
```
@java -jar $(BOB_FILE) \
	--settings game.project \
	--settings game.project.ios \
	--settings game.project.release \
	--settings game.project.build \
	--texture-compression true \
	--identity xxxxxx \
	--mobileprovisioning production.mobileprovision \
	--bundle-output dist \
	--build-report-html build/report.html \
	--variant release \
	--archive \
	--architectures arm64-ios, x86_64-ios \
	--platform arm64-ios \
	--with-symbols \
	--use-async-build-server \
	resolve clean distclean build bundle
```

**Comment by britzl** [comment]
We are working on Cocoapod Swift support.

**Comment by britzl** [comment]
Cocoapos Swift support has been added.
