### ISSUE TITLE
ios build fails

### ISSUE THREAD

**Issue by SalavatR** [defold/extender#316]
Hi!
try to build iOS, bob 1.4.7, with applovin plugin and got error on both
--build-server https://build-stage.defold.com/ and without, 

here is log file
[log1.txt](https://github.com/defold/extender/files/12525409/log1.txt)

last known work date is 29.08.2023

dependency link: https://github.com/HGPoint/defold-maxsdk/archive/refs/tags/11.11.3.0.zip
this pod causes error `pod 'AppLovinMediationByteDanceAdapter', '5.4.1.0.0' `

.project applovin config
```
[applovin]
sdk_key_ios = xxxx
ad_unit_rewarded = xxx
ad_unit_interstitial = xxx
ad_unit_banner = xxx
amazon_key = xxx
amazon_interstitial_slot = xxxx
amazon_banner_slot = xxxx
ByteDanceAdapter = 1
```

build command
```
@java -jar $(BOB_FILE) \
	--settings game.project \
	--settings game.project.ios \
	--settings game.project.release \
	--settings game.project.build \
	--texture-compression true \
	--identity xxxxxx \
	--mobileprovisioning production.mobileprovision \
	--bundle-output dist \
	--build-report-html build/report.html \
	--variant release \
	--archive \
	--architectures arm64-ios, x86_64-ios \
	--platform arm64-ios \
	--with-symbols \
	--use-async-build-server \
	resolve clean distclean build bundle
```

**Comment by britzl** [comment]
```
0  0x1061ddf7a  __assert_rtn + 139
1  0x1061ea0c3  ld::tool::SymbolTableAtom<arm64>::encode() (.cold.1) + 35
2  0x1060d56c3  ld::tool::SymbolTableAtom<arm64>::encode() + 1475
3  0x1060c047e  ___ZN2ld4tool10OutputFile20buildLINKEDITContentERNS_8InternalE_block_invoke_3 + 30
4  0x7fff202a7623  _dispatch_call_block_and_release + 12
5  0x7fff202a8806  _dispatch_client_callout + 8
6  0x7fff202b7acd  _dispatch_root_queue_drain + 1019
7  0x7fff202b7f70  _dispatch_worker_thread2 + 92
8  0x7fff2044f417  _pthread_wqthread + 244
A linker snapshot was created at:
	/tmp/dmengine-2023-09-05-151919.ld-snapshot
ld: Assertion failed: (_machoSection != 0), function machoSection, file ld.hpp, line 1311.
clang: error: linker command failed with exit code 1 (use -v to see invocation)

	at com.defold.extender.Extender.buildEngine(Extender.java:2006)
	at com.defold.extender.Extender.build(Extender.java:2336)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:115)
	at com.defold.extender.AsyncBuilder$$FastClassBySpringCGLIB$$3a887347.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:115)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by britzl** [comment]
I honestly have no idea what's going on here. It also crashes with the latest version (5.5.0.7.0). Linker command:

```
cd /private/var/folders/11/46kfq53d3qg84mb4gjdm5hk40000gn/T/job4319966900207603339
/Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/bin/ld -demangle -lto_library /Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/lib/libLTO.dylib -dynamic -arch arm64 -dead_strip -platform_version ios 11.0.0 16.2 -syslibroot /Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk -ObjC -o build/dmengine -L/var/folders/11/46kfq53d3qg84mb4gjdm5hk40000gn/T/job4319966900207603339/build -L/var/folders/11/46kfq53d3qg84mb4gjdm5hk40000gn/T/job4319966900207603339/CocoaPodsService/frameworks/lib/arm64-ios -L/Users/bjornritzl/projects/defold/tmp/dynamo_home//lib/arm64-ios -L/Users/bjornritzl/projects/defold/tmp/dynamo_home//ext/lib/arm64-ios -L/Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/usr/lib -L/Users/bjornritzl/extender/platformsdk/iPhoneOS16.2.sdk/usr/lib/swift -L/Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/lib/swift-5.5/iphoneos -L/Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/lib/swift/iphoneos -L/Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/lib/clang/14.0.0/lib/darwin -U _objc_loadClassref -lclang_rt.ios -lz -lbz2 -lresolv.9 -lc++ -lsqlite3 -lxml2 -lc++abi -liconv -lresolv -lFirebase_1 -lByteDanceAdapter -lBURelyFoundationGlobalZip -lBURelyFoundationGlobalZFPlayer -lBURelyFoundationGlobalYYModel -lBURelyFoundationGlobalSDWebImage -lBURelyFoundationGlobalNETWork -lBURelyFoundationGlobalHeader -lBURelyFoundationGlobalGecko -lBURelyFoundationGlobalFoundation -lBURelyFoundationGlobalAPM -lBURelyFoundationGlobalAFN -framework AppLovinSDK -framework BURelyAdSDK -framework PAGAdSDK -framework OpenGLES -framework OpenAL -framework QuartzCore -framework CoreGraphics -framework AudioToolbox -framework SystemConfiguration -framework CoreVideo -framework UIKit -framework AVFoundation -framework UIKit -framework CoreFoundation -framework WebKit -framework StoreKit -framework CoreServices -framework MediaPlayer -framework CoreMedia -framework AVFoundation -framework CoreTelephony -framework SystemConfiguration -framework AdSupport -framework CoreMotion -framework Accelerate -framework Security -framework AudioToolbox -framework CFNetwork -framework CoreGraphics -framework MessageUI -framework SafariServices -framework MobileCoreServices -framework JavaScriptCore -framework CoreImage -framework ImageIO -framework QuartzCore -framework CoreText -weak_framework Foundation -weak_framework AppTrackingTransparency -weak_framework CoreML -weak_framework DeviceCheck -lengine -lengine_service -lmbedtls -lzip -lwebviewext -lprofile -lremotery -lprofilerext -lfacebookext -liapext -lpushext -liacext -lrecord_null -lgameobject -lddf -lresource -lgamesys -lgraphics -lgraphics_transcoder_basisu -lbasis_transcoder -lphysics -lBulletDynamics -lBulletCollision -lLinearMath -lBox2D -lrender -lscript -lluajit-5.1 -lextension -lhid -linput -lparticle -lrig -ldlib -ldmglfw -lgui -lcrashext -lsound -ltremolo -lliveupdate -lresolv build/main_tmp2.o -framework Foundation -lobjc -lc++ -lSystem /Users/bjornritzl/extender/platformsdk/XcodeDefault14.2.xctoolchain/usr/lib/clang/14.0.0/lib/darwin/libclang_rt.ios.a -F/var/folders/11/46kfq53d3qg84mb4gjdm5hk40000gn/T/job4319966900207603339/build -F/var/folders/11/46kfq53d3qg84mb4gjdm5hk40000gn/T/job4319966900207603339/CocoaPodsService/frameworks/lib/arm64-ios
```

**Comment by AGulev** [comment]
It works in Defold 1.6.2 and https://build.defold.com/ (now it uses xcode 15.0.1)
