### ISSUE TITLE
moshi-1.14.0: Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 60

### ISSUE THREAD

**Issue by ekharkunov** [defold/extender#405]
After enabling standalone jetifier (#400, #301) Zendesk extension cannot be built for Android platform (https://github.com/defold/test-sdk/actions/runs/10136526116/job/28025435982#step:4:713)
```
Error: Exception in thread "main" java.lang.IllegalArgumentException: Unsupported class file major version 60
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:196)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:177)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:163)
	at com.android.tools.build.jetifier.processor.transform.bytecode.ByteCodeTransformer.runTransform(ByteCodeTransformer.kt:35)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:592)
	at com.android.tools.build.jetifier.processor.archive.ArchiveFile.accept(ArchiveFile.kt:59)
	at com.android.tools.build.jetifier.processor.Processor.visit(Processor.kt:574)
	at com.android.tools.build.jetifier.processor.archive.Archive.accept(Archive.kt:78)
	at com.android.tools.build.jetifier.processor.Processor.transformLibrary(Processor.kt:570)
	at com.android.tools.build.jetifier.processor.Processor.transform2(Processor.kt:335)
	at com.android.tools.build.jetifier.processor.Processor.transform2$default(Processor.kt:295)
	at com.android.tools.build.jetifier.standalone.Main.run(Main.kt:181)
	at com.android.tools.build.jetifier.standalone.Main$Companion.main(Main.kt:119)
	at com.android.tools.build.jetifier.standalone.Main.main(Main.kt)

	at com.defold.extender.services.RealGradleService.execCommand(RealGradleService.java:180)
	at com.defold.extender.services.RealGradleService.runJetifier(RealGradleService.java:289)
	at com.defold.extender.services.RealGradleService.resolveDependencyJAR(RealGradleService.java:238)
	at com.defold.extender.services.RealGradleService.unpackDependencies(RealGradleService.java:260)
	at com.defold.extender.services.RealGradleService.downloadDependencies(RealGradleService.java:282)
	at com.defold.extender.services.RealGradleService.resolveDependencies(RealGradleService.java:106)
	at com.defold.extender.services.GradleService.resolveDependencies(GradleService.java:22)
	at com.defold.extender.Extender.resolve(Extender.java:2552)
	at com.defold.extender.AsyncBuilder.asyncBuildEngine(AsyncBuilder.java:105)
	at jdk.internal.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:354)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:768)
	at org.springframework.aop.interceptor.AsyncExecutionInterceptor.lambda$invoke$0(AsyncExecutionInterceptor.java:113)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

Related posts in google issue tracker:
https://issuetracker.google.com/issues/209825727
https://issuetracker.google.com/issues/184622491
The main idea is not to run `jetifier` for dependencies that aren't needed to migrate to AndroidX.
Possible solution:
Before running `jetifier` execute 
```sh
./graldew checkJetifier
```
and get list of dependencies that need to be jetified. There is no good approach to get list of dependencies in Groovy code (or I can't find it).

**Comment by ekharkunov** [comment]
Changes was reverted https://github.com/defold/extender/pull/411
