### ISSUE TITLE
Manifest merge errror: java.lang.NoClassDefFoundError: com/android/sdklib/SdkVersionInfo

### ISSUE THREAD

**Issue by ekharkunov** [defold/extender#418]
I Extender's logs I found following error:
```
Exception in thread "main" java.lang.NoClassDefFoundError: com/android/sdklib/SdkVersionInfo 
	at com.android.manifmerger.XmlDocument.getApiLevelFromAttribute(XmlDocument.java:545) 
	at com.android.manifmerger.XmlDocument.getExplicitVersionAttribute(XmlDocument.java:404) 
	at com.android.manifmerger.XmlDocument.getExplicitTargetSdkVersion(XmlDocument.java:363) 
	at com.android.manifmerger.XmlDocument.getRawTargetSdkVersion(XmlDocument.java:424) 
	at com.android.manifmerger.XmlDocument.getImplicitElementsToAdd(XmlDocument.java:596) 
	at com.android.manifmerger.XmlDocument.merge(XmlDocument.java:203) 
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:1178) 
	at com.android.manifmerger.ManifestMerger2.merge(ManifestMerger2.java:377) 
	at com.android.manifmerger.ManifestMerger2$Invoker.merge(ManifestMerger2.java:2148) 
	at com.defold.manifestmergetool.AndroidManifestMerger.merge(AndroidManifestMerger.java:58) 
	at com.defold.manifestmergetool.ManifestMergeTool.mergeAndroid(ManifestMergeTool.java:36) 
	at com.defold.manifestmergetool.ManifestMergeTool.merge(ManifestMergeTool.java:84) 
	at com.defold.manifestmergetool.ManifestMergeTool.main(ManifestMergeTool.java:136) 
Caused by: java.lang.ClassNotFoundException: com.android.sdklib.SdkVersionInfo 
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) 
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) 
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) 

```
Some information related to that error:
https://git.gugelfrei.de/gugelfrei/android_build/commit/0084dc8e2f9840ea0f80015072f4da3d64e83e5d

**Comment by ekharkunov** [comment]
After some investigation found following things:
* Earlier it allowed to use codenames in `<uses-sdk>` tag like "UpsideDownCake"
* If use codename instead of integer version - result manifest also contains codename as value inside `<uses-sdk>`
* Bundle with codename inside `<uses-sdk>` failed to create.
* Manifest merge library contains following comments regarding `<uses-sdk>` attributes
```
    /**
     * Returns the maxSdk version specified in the uses_sdk element if present in the
     * AndroidManifest.xml file, or null if not explicitly specified.
     *
     * <p>Note that specifying this value in the AndroidManifest.xml file is now ignored, generates
     * a warning and will be an error in 8.0).
     */
    @Nullable
    private String getExplicitMaxSdkVersion(@NonNull MergingReport.Builder mergingReport) {
        return getExplicitVersionAttribute("android:maxSdkVersion", mergingReport);
    }
```

So closing for now as no action needed. Pay attention in future updates if any changes will be made in terms of how sdk version handled.
